services:
  db:
    image: postgres
    ports:
      - "5500:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=universityManager
      - POSTGRES_USER=universityManager
      - POSTGRES_DB=universityManager